pasign/urls.py
from django.contrib import admin
from django.urls import path
from app.views import (LandingPageView, LoginPageView, DashboardView, ForgotPassView, TestView, UploadView, register_user, get_student_data)
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', LandingPageView.as_view(landing_page='index.html'), name='landing_page'),
    path('login/', LoginPageView.as_view(login_page='login-index.html'), name='login_page'),
    path('forgotpass/', ForgotPassView.as_view(), name='forgotpassword'),
    path('dashboard/', DashboardView.as_view(), name='dashboard_page'),
    path('upload/', UploadView.as_view(), name='upload_data'),
    path('register/', register_user, name='register_user'),
    path('test/', TestView.as_view(), name='test_data'),
    path('get-student-data/<str:student_id>/', get_student_data, name='get_student_data'),
]

# Serve media files during development
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/models.py
from django.db import models
import os

def get_user_signature_path(instance, filename):
    """
        Creates a folder for each user using their student_id

        Example:
        >>> instance = UserData(student_id='1234567890')
        >>> get_user_signature_path(instance, 'signature_1.png')
        'Student 1234567890/signature_1.png'
        >>> get_user_signature_path(instance, 'signature_2.png')
        'Student 1234567890/signature_2.png'
        >>> get_user_signature_path(instance, 'signature_3.png')
        'Student 1234567890/signature_3.png'
    """
    folder_name = f"Student {instance.student_id}"
    return os.path.join(folder_name, filename)

class UserData(models.Model):
    first_name = models.CharField(max_length=255)
    last_name = models.CharField(max_length=255)
    student_id = models.CharField(max_length=15)
    email = models.EmailField()
    signature_1 = models.FileField(upload_to=get_user_signature_path, blank=True, null=True)
    signature_2 = models.FileField(upload_to=get_user_signature_path, blank=True, null=True)
    signature_3 = models.FileField(upload_to=get_user_signature_path, blank=True, null=True)
    signature_4 = models.FileField(upload_to=get_user_signature_path, blank=True, null=True)
    signature_5 = models.FileField(upload_to=get_user_signature_path, blank=True, null=True)
    signature_6 = models.FileField(upload_to=get_user_signature_path, blank=True, null=True)
    signature_7 = models.FileField(upload_to=get_user_signature_path, blank=True, null=True)
    signature_8 = models.FileField(upload_to=get_user_signature_path, blank=True, null=True)
    signature_9 = models.FileField(upload_to=get_user_signature_path, blank=True, null=True)
    signature_10 = models.FileField(upload_to=get_user_signature_path, blank=True, null=True)
    signature_11 = models.FileField(upload_to=get_user_signature_path, blank=True, null=True)
    signature_12 = models.FileField(upload_to=get_user_signature_path, blank=True, null=True)
    signature_13 = models.FileField(upload_to=get_user_signature_path, blank=True, null=True)
    signature_14 = models.FileField(upload_to=get_user_signature_path, blank=True, null=True)
    signature_15 = models.FileField(upload_to=get_user_signature_path, blank=True, null=True)
    signature_16 = models.FileField(upload_to=get_user_signature_path, blank=True, null=True)
    signature_17 = models.FileField(upload_to=get_user_signature_path, blank=True, null=True)
    signature_18 = models.FileField(upload_to=get_user_signature_path, blank=True, null=True)
    signature_19 = models.FileField(upload_to=get_user_signature_path, blank=True, null=True)
    signature_20 = models.FileField(upload_to=get_user_signature_path, blank=True, null=True)
    signature_21 = models.FileField(upload_to=get_user_signature_path, blank=True, null=True)
    signature_22 = models.FileField(upload_to=get_user_signature_path, blank=True, null=True)
    signature_23 = models.FileField(upload_to=get_user_signature_path, blank=True, null=True)
    signature_24 = models.FileField(upload_to=get_user_signature_path, blank=True, null=True)
    signature_25 = models.FileField(upload_to=get_user_signature_path, blank=True, null=True)

    def __str__(self):
        return f"{self.first_name} {self.last_name}"

app/templates/dashboard.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'dashboard/dashboard.css' %}">

    <title>Dashboard</title>
    
    <!DOCTYPE html>

</head>
<body>
        
    <div class="navigation">
        <a class="button" href="{% url 'landing_page' %}">
            <img src="{% static 'dashboard/logout.png' %}">
            <div class="logout">LOGOUT</div>
        </a>
    </div>

    <div class="container">
        <button type="button" class="btn cube cube-hover" id="uploadButton">
            <div class="bg-top">
                <div class="bg-inner"></div>
            </div>
            <div class="bg-right">
                <div class="bg-inner"></div>
            </div>
            <div class="bg">
                <div class="bg-inner"></div>
            </div>
            <div class="text">UPLOAD DATA</div>
        </button>

        <button type="button" class="btn cube cube-hover" id="testButton">
            <div class="bg-top">
                <div class="bg-inner"></div>
            </div>
            <div class="bg-right">
                <div class="bg-inner"></div>
            </div>
            <div class="bg">
                <div class="bg-inner"></div>
            </div>
            <div class="text">TEST DATA</div>
        </button>
    </div>



    <script>
        document.getElementById("uploadButton").addEventListener("click", function () {
            window.location.href = "{% url 'upload_data' %}";
        });

        document.getElementById("testButton").addEventListener("click", function () {
            window.location.href = "{% url 'test_data' %}";
        });
    </script>


<script src="{% static 'dashboard/dashboard.js' %}"></script>

</body>
</html>

app/templates/forgotpass.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <title>Forgot Password</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link href="https://fonts.googleapis.com/css?family=Lato:300,400,700&display=swap" rel="stylesheet">

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">

    <link rel="stylesheet" href="{% static 'forgotpass/css/forgotpass.css' %}">

</head>
<body>

<section class="ftco-section">
    <div class="top-gradient"></div>
  <div class="bottom-gradient"></div>
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-10">
                <div class="wrap d-md-flex">
                    <div class="form-group text-center">
                        <a href="{% url 'login_page' %}" class="btn btn-secondary">
                            <i class="fa fa-arrow-left"></i>
                        </a>
                    </div>                    
                    <div class="img" style="background-image: url(images/log.gif);"></div>
                    <div class="login-wrap p-4 p-md-5">
                        <div class="d-flex">
                            <div class="w-100">
                                <h3 class="mb-4" style="text-align: center;">PASIGN</h3>
                            </div>
                        </div>
                        <form action="#" class="signin-form">
                            <div class="form-group text-center mb-3">
                                <p>No problem, we’ll email you instructions to reset your password.</p>
                            </div>
                            <div class="form-group mb-3 text-center">
                                <label class="label" for="email"></label>
                                <input type="email" class="form-control" placeholder="Enter your Corporate Email" required>
                            </div>
                            <div class="form-group text-center">
                                <button type="submit" class="form-control btn btn-primary rounded submit px-3">Reset Password</button>
                            </div>
                        </form>
                        <div class="form-group text-center">
                            <a href="{% url 'login_page' %}" class="btn btn-link btn-no-hover">
                                <span style="font-size: 24px; cursor: pointer;">&larr;</span> Back to Login
                            </a>
                        </div>                    
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

<script src="js/jquery.min.js"></script>
<script src="js/popper.js"></script>
<script src="js/bootstrap.min.js"></script>
<script src="js/main.js"></script>

</body>
</html>

app/templates/index.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
    
    <head>
        <meta charset=utf-8>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Signature Authenticity</title>
        <!-- Load Roboto font -->
        <link href='http://fonts.googleapis.com/css?family=Roboto:400,300,700&amp;subset=latin,latin-ext' rel='stylesheet' type='text/css'>
        <!-- Load css styles -->
<!-- project/templates/landing/index.html -->

        <link rel="stylesheet" type="text/css" href="{% static 'landingpage/css/bootstrap.css' %}" />
        <link rel="stylesheet" type="text/css" href="{% static 'landingpage/css/bootstrap-responsive.css' %}" />
        <link rel="stylesheet" type="text/css" href="{% static 'landingpage/css/style.css' %}" />
        <link rel="stylesheet" type="text/css" href="{% static 'landingpage/css/pluton.css' %}" />
        <!--[if IE 7]>
            <link rel="stylesheet" type="text/css" href="{% static 'app/css/pluton-ie7.css' %}" />
        <![endif]-->
        <link rel="stylesheet" type="text/css" href="{% static 'landingpage/css/jquery.cslider.css' %}" />
        <link rel="stylesheet" type="text/css" href="{% static 'landingpage/css/jquery.bxslider.css' %}" />
        <link rel="stylesheet" type="text/css" href="{% static 'landingpage/css/animate.css' %}" />

        <!-- Fav and touch icons -->
        <link rel="apple-touch-icon-precomposed" sizes="144x144" href="images/ico/apple-touch-icon-144.png">
        <link rel="apple-touch-icon-precomposed" sizes="114x114" href="images/ico/apple-touch-icon-114.png">
        <link rel="apple-touch-icon-precomposed" sizes="72x72" href="images/apple-touch-icon-72.png">
        <link rel="apple-touch-icon-precomposed" href="images/ico/apple-touch-icon-57.png">
        <link rel="shortcut icon" href="images/ico/favicon.ico">
    </head>
    
    <body>
        <div class="navbar">
            <div class="navbar-inner">
                <div class="container">
                    <!-- Navigation button, visible on small resolution -->
                    <button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                        <i class="icon-menu"></i>
                    </button>
                    <!-- Main navigation -->
                    <div class="nav-collapse collapse pull-right">
                        <ul class="nav" id="top-navigation">
                            <li class="active"><a href="#home">Home</a></li>
                            <li><a href="#service">Do's</a></li>
                            <li><a href="#about">About</a></li>
                        </ul>
                    </div>
                    <!-- End main navigation -->
                </div>
            </div>
        </div>
        <!-- Start home section -->
        <div id="home">
            <!-- Start cSlider -->
            <div id="da-slider" class="da-slider">
                <div class="triangle"></div>
                <!-- mask elemet use for masking background image -->
                <div class="mask"></div>
                <!-- All slides centred in container element -->
                <div class="container">
                    <!-- Start first slide -->
                    <div class="da-slide">
                        <h2 class="fittext2">Welcome to Pasign</h2>
                        <h4>PROVING HANDWRITTEN <br> SIGNATURE USING SIAMESE NEURAL NETWORK</h4>
                        <p>Ensure the validity of handwritten signatures through cutting-edge Siamese neural network technology, providing advanced verification and authentication of handcrafted signatures with unparalleled precision and security.</p>
                        <a href="{% url 'login_page' %}" class="da-link button">LOGIN</a>
                        <div class="da-img">
                            <img src="{% static 'landingpage/images/penwrite.png' %}" alt="image01" width="350">
                        </div>
                    </div>
                    <!-- End first slide -->
                    <!-- Start second slide -->
                    <div class="da-slide">
                        <h2>GENUINE SIGNATURE</h2>
                        <h4>AUTHENTICITY SPEAKS VOLUMES IN <br> EVERY GENUINE SIGNATURE</h4>
                        <p>A Genuine Signature is a unique and unmistakable expression of one's true self. It transcends mere ink on paper, embodying the essence and integrity of an individual's thoughts, beliefs, and intentions.</p>
                        <a href="{% url 'login_page' %}" class="da-link button">LOGIN</a>
                        <div class="da-img">
                            <img src="{% static 'landingpage/images/pen.png' %}" width="320" alt="image02">
                        </div>
                    </div>
                    <!-- End second slide -->
                    <!-- Start third slide -->
                    <div class="da-slide">
                        <h2>FORGED SIGNATURE</h2>
                        <h4>A FRAUDULENT REPLICATION OF A <br> PERSON'S MARK, UNDERMINING TRUST</h4>
                        <p>This act involves skilled imitation, aiming to deceive and manipulate documents, contracts, or agreements. It undermines the integrity of signatures, eroding the foundation of trust that such marks are meant to symbolize. </p>
                        <a href="{% url 'login_page' %}" class="da-link button">LOGIN</a>
                        <div class="da-img">
                            <img src="{% static 'landingpage/images/paper.png' %}" width="320" alt="image03">
                        </div>
                    </div>
                    <!-- Start third slide -->
                    <!-- Start cSlide navigation arrows -->
                    <div class="da-arrows">
                        <span class="da-arrows-prev"></span>
                        <span class="da-arrows-next"></span>
                    </div>
                    <!-- End cSlide navigation arrows -->
                </div>
            </div>
        </div>
        <!-- End home section -->

        <!-- Service section start -->
        <div class="section primary-section" id="service">
            <div class="container">
                <!-- Start title section -->
                <div class="title">
                    <h1>What We Do?</h1>
                    <!-- Section's title goes here -->
                    <p>We leverage state-of-the-art Siamese Neural Network technology to achieve impressive signature accuracy rates.</p>
                    <!--Simple description for section goes here. -->
                </div>
                <div class="row-fluid">
                    <div class="span4">
                        <div class="centered service">
                            <div class="circle-border zoom-in">
                                <img class="img-circle" src="{% static 'landingpage/images/uploadbg.jpg' %}" alt="service 1" style="border: 3px solid #FECE1A;">
                            </div>
                            <h3>UPLOAD DATA</h3>
                            <p>This initial step involves inputting the relevant signature data into the system. This can include scanned images or digital files of signatures to be verified.</p>
                        </div>
                    </div>
                    <div class="span4">
                        <div class="centered service">
                            <div class="circle-border zoom-in">
                                <img class="img-circle" src="{% static 'landingpage/images/testbg.jpg' %}" alt="service 2" style="border: 3px solid #FECE1A;">
                            </div>
                            <h3>TEST</h3>
                            <p>Once the data is uploaded, the system initiates the verification process. It employs advanced algorithms to analyze the provided signature against reference samples.</p>
                        </div>
                    </div>
                    <div class="span4">
                        <div class="centered service">
                            <div class="circle-border zoom-in">
                                <img class="img-circle" src="{% static 'landingpage/images/resultbg.jpg' %}" alt="service 3" style="border: 3px solid #FECE1A;">
                            </div>
                            <h3>GET RESULT</h3>
                            <p>This step delivers a percentage-based evaluation, indicating the degree of similarity between the provided signature and the reference data, ensuring a concise outcome.</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- Service section end -->

        <div class="section secondary-section">
            <div class="triangle"></div>
            <div class="container centered">
                <p class="large-text">Your handwritten signature is a personal imprint, a unique expression of your identity and intention, capturing a moment in time with a stroke of the pen</p>
            </div>
        </div>
        
        <!-- About us section start -->
        <div class="section primary-section" id="about">
            <div class="triangle"></div>
            <div class="container">
                <div class="title">
                    <h1>Who We Are?</h1>
                    <p>COMPUTER SCIENCE STUDENT RESEARCHERS</p>
                </div>
                <div class="row-fluid team">
                    <div class="span3" id="first-person">
                        <div class="thumbnail">
                            <img src="{% static 'landingpage/images/Myk.JPG' %}" alt="team 1">
                            <h3>Abad, Mykel Zandrex P.</h3>
                            
                            <div class="mask">
                                <h2>BSCS 4B-1</h2>
                            </div>
                        </div>
                    </div>
                    <div class="span3" id="second-person">
                        <div class="thumbnail">
                            <img src="{% static 'landingpage/images/Carl.JPG' %}" alt="team 2">
                            <h3>Alabastro, Carl Vincent</h3>
                            
                            <div class="mask">
                                <h2>BSCS 4B-1</h2>
                            </div>
                        </div>
                    </div>
                    <div class="span3" id="third-person">
                        <div class="thumbnail">
                            <img src="{% static 'landingpage/images/Dans.JPG' %}" alt="team 3">
                            <h3>Danay, Leizel Ann M.</h3>
                            
                            <div class="mask">
                                <h2>BSCS 4B-1</h2>
                            </div>
                        </div>
                    </div>
                    <div class="span3" id="fourth-person">
                        <div class="thumbnail">
                            <img src="{% static 'landingpage/images/Ralph.JPG' %}" alt="team 4">
                            <h3>De Paz, John Ralph A.</h3>
                            
                            <div class="mask">
                                <h2>BSCS 4B-1</h2>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="about-text centered">
                    {% comment %} <h3>About Us</h3> {% endcomment %}
                    <p>-------------------------------------------------------------------
                    </p>
                </div>
            </div>
        </div>
        <!-- About us section end -->  

       
        
        <!-- Footer section start -->
        <div class="footer">

        </div>
        <!-- Footer section end -->
        <!-- ScrollUp button start -->
        <div class="scrollup">
            <a href="#">
                <i class="icon-up-open"></i>
            </a>
        </div>
        <!-- ScrollUp button end -->
        <!-- Include javascript -->
        <script src="{% static 'landingpage/js/jquery.js' %}"></script>
        <script type="text/javascript" src="{% static 'landingpage/js/jquery.mixitup.js' %}"></script>
        <script type="text/javascript" src="{% static 'landingpage/js/bootstrap.js' %}"></script>
        <script type="text/javascript" src="{% static 'landingpage/js/modernizr.custom.js' %}"></script>
        <script type="text/javascript" src="{% static 'landingpage/js/jquery.bxslider.js' %}"></script>
        <script type="text/javascript" src="{% static 'landingpage/js/jquery.cslider.js' %}"></script>
        <script type="text/javascript" src="{% static 'landingpage/js/jquery.placeholder.js' %}"></script>
        <script type="text/javascript" src="{% static 'landingpage/js/jquery.inview.js' %}"></script>
        <script type="text/javascript" src="{% static 'landingpage/js/app.js' %}"></script>

        <!-- Load google maps api and call initializeMap function defined in app.js -->
        <script async="" defer="" type="text/javascript" src="https://maps.googleapis.com/maps/api/js?sensor=false&callback=initializeMap"></script>
        <!-- css3-mediaqueries.js for IE8 or older -->
        <!--[if lt IE 9]>
            <script src="js/respond.min.js"></script>
        <![endif]-->
    </body>
</html>

app/templates/login-index.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <title>Login</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link href="https://fonts.googleapis.com/css?family=Lato:300,400,700&display=swap" rel="stylesheet">

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">

    <link rel="stylesheet" href="{% static 'login/css/login.css' %}">

</head>
<body>

<section class="ftco-section">
    <div class="top-gradient"></div>
    <div class="bottom-gradient"></div>
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-10">
                <div class="wrap d-md-flex">
                    <div class="form-group text-center">
                        <a href="{% url 'landing_page' %}" class="btn btn-secondary">
                            <i class="fa fa-arrow-left"></i>
                        </a>
                    </div>                    
                    <!-- app/templates/app/landing/index.html -->
                    <div class="img background-image"></div>
                    <div class="login-wrap p-4 p-md-5">
                        <div class="d-flex">
                            <div class="w-100">
                                <h3 class="mb-4" style="text-align: center;">PASIGN</h3>
                            </div>
                        </div>
                        <!-- LOGIN PART -->
                        <form action="{% url 'login_page' %}" method="post" class="signin-form">
                            {% csrf_token %}
                            {% if error_message %}
                                <div class="alert alert-danger" role="alert" style="font-size: 14px;">
                                    {{ error_message }}
                                </div>
                            {% endif %}
                            <div class="form-group mb-3">
                                <label class="label" for="name">Username</label>
                                <input type="text" name="username" class="form-control" placeholder="Username" required>
                            </div>
                            <div class="form-group mb-3">
                                <label class="label" for="password">Password</label>
                                <input type="password" name="password" class="form-control" placeholder="Password" required>
                            </div>
                            <div class="form-group">
                                <button type="submit" class="form-control btn btn-primary rounded submit px-3" id="loginButton">Login</button>
                            </div>
                            
                            <div class="form-group d-md-flex">
                                <div class="w-50 text-left">
                                    <label class="checkbox-wrap checkbox-primary mb-0">Remember Me
                                        <input type="checkbox" name="remember_me" {% if request.COOKIES.remember_me %}checked{% endif %}>
                                        <span class="checkmark"></span>
                                    </label>
                                </div>
                                {% comment %} <div class="w-50 text-md-right">
                                    <a href="{% url 'forgotpassword' %}">Forgot Password?</a>
                                </div> {% endcomment %}
                            </div>
                        </form>
      
                        <div class="form-group text-center">
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

<script src="{% static 'login/js/jquery.min.js' %}"></script>
<script src="{% static 'login/js/popper.js' %}"></script>
<script src="{% static 'login/js/bootstrap.min.js' %}"></script>
<script src="{% static 'login/js/login.js' %}"></script>


</body>
</html>

app/templates/upload.html
{% load static %}

<!DOCTYPE html>
<html lang="en" >
<head>
  <meta charset="UTF-8">
  <title>Upload Data</title>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/meyer-reset/2.0/reset.min.css">
  <link rel="stylesheet" href="{% static 'upload/upload.css' %}">
</head>
<body>
  
  <main class="demo-page-content">  
    <section>
      <div class="row">
        <div class="column">
          <div class="href-target" id="input-types"></div>
          <h1>REGISTER SIGNATURE</h1>
          <p>Input Data & Signatures</p>
        </div>

        <a href="{% url 'dashboard_page' %}" style="text-decoration:none">
          <div class="container1">
            <button class="button1">
              <div class="flex-container">
                <div class="text1">
                  Back
                </div>
                <svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-arrow-back-up" 
                     width="24" height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" 
                     stroke-linecap="round" stroke-linejoin="round">
                  <path stroke="none" d="M0 0h24v24H0z" fill="none"/>
                  <path d="M9 13l-4 -4l4 -4m-4 4h11a4 4 0 0 1 0 8h-1" />
                </svg>
              </div>
            </button>
          </div>
        </a>
      </div>

        <form action="{% url 'register_user' %}" method="post" enctype="multipart/form-data">
          {% csrf_token %}
      
          <div class="name-container">
              <div class="nice-form-group">
                  <label for="id_first_name">First Name</label>
                  <input type="text" id="id_first_name" name="first_name" placeholder="Your firstname" required />
              </div>
      
              <div class="nice-form-group">
                  <label for="id_last_name">Last Name</label>
                  <input type="text" id="id_last_name" name="last_name" placeholder="Your lastname" required />
              </div>
          </div>
      
          <div class="nice-form-group">
              <label for="id_student_id">Student ID Number</label>
              <input type="text" id="id_student_id" name="student_id" placeholder="0000-0-0000" required />
          </div>
      
          <div class="nice-form-group">
              <label for="id_email">Email</label>
              <input type="email" id="id_email" name="email" placeholder="0000-0-0000@psu.palawan.edu.ph" required />
          </div>
      
          <!-- <div class="nice-form-group">
              <label for="id_signature_type">Select Signature Type</label>
              <select id="id_signature_type" name="signature_type" required>
                  <option disabled selected>Please select a signature type</option>
                  <option>Current Signature</option>
                  <option>Old Signature</option>
              </select>
          </div> -->
      
          <div class="nice-form-group">
              <label for="id_signature_files">File upload</label>
              <input type="file" accept="image/*" id="id_signature_files" name="signature_files" multiple required />
          </div>
      
          <br>

          {% if messages %}
                {% for message in messages %}
                    <div id="success-message" class="alert alert-success text-center" role="alert" style="color: green;">
                        {{ message }}
                    </div>
                {% endfor %}
            {% endif %}
      
          <div class="container">
              <button class="button" type="submit">
                  <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
                      <path stroke-linecap="round" stroke-linejoin="round" d="M4.5 12h15m0 0l-6.75-6.75M19.5 12l-6.75 6.75"></path>
                  </svg>
                  <div class="text">
                      Submit
                  </div>
              </button>
          </div>
      </form>
    </section>
  </main>

  <script src="{% static 'upload/upload.js' %}"></script>
</body>
</html>